# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 91a740216ca74ca3e60b039531f046b970ba24a4e988e879e624b23e1887bce2eef3d4f518ad1ca2efdc9347a7c4a2cec5937811000e6069b5691b2790fd09a2

test:
  secret_key_base: 86c706fec5b29520d985d913693551ca477669f011a7e6e45778194a0eafb961fd7e09fa1a74f5b4a406a0925986677ffbbc5fab97a8e8f741d0e7ff058d2cc5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
